### ISSUE TITLE
argparse.ArgumentError: argument subcommand: conflicting subparser: get_repo_news_path

### ISSUE THREAD

**Issue by Hello71** [pkgcore/pkgcore#347]
when installing pkgcore 0.12.11 or master with Python 3.11:

```
Generating plugin cache
Traceback (most recent call last):
  File "/tmp/pkgcore/./setup.py", line 240, in <module>
    setup(**dict(
    ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 177, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
    dist.run_commands()
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
    ^^^^^^^^^^^^^
  File "/tmp/pkgcore/./setup.py", line 60, in run
    plugin.initialize_cache(plugins, force=True, cache_dir=path)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pkgcore/src/pkgcore/plugin.py", line 235, in initialize_cache
    module = import_module(qualname)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 939, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/tmp/pkgcore/src/pkgcore/plugins/builtin_configurables.py", line 15, in <module>
    for module in walker().walk_namespace('pkgcore'):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/snakeoil/test/mixins.py", line 95, in get_modules
    yield self.poor_mans_load(namespace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/snakeoil/test/mixins.py", line 152, in poor_mans_load
    obj = __import__(namespace)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pkgcore/src/pkgcore/scripts/pinspect.py", line 330, in <module>
    _portageq.bind_parser(portageq, compat=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pkgcore/src/pkgcore/ebuild/portageq.py", line 266, in bind_parser
    subparser = subparsers.add_parser(
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/pkgcore/src/pkgcore/util/commandline.py", line 517, in add_parser
    return super().add_parser(name, config=config, domain=domain, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/snakeoil/cli/arghparse.py", line 474, in add_parser
    parser = super().add_parser(name, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/snakeoil/klass.py", line 645, in wrapper
    return func(orig_func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/snakeoil/cli/arghparse.py", line 52, in _add_argument_docs
    obj = orig_func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/argparse.py", line 1185, in add_parser
    raise ArgumentError(self, _('conflicting subparser: %s') % name)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
argparse.ArgumentError: argument subcommand: conflicting subparser: get_repo_news_path
```

**Comment by arthurzam** [comment]
Can you please try again with newest versions of snakeoil and pkgcore? I think it was fixed with those releases.

**Comment by Hello71** [comment]
snakeoil works but pkgcore 0.12.12 and master are still not working, same error.

**Comment by thesamesam** [comment]
Should be fixed by https://github.com/pkgcore/pkgcore/commit/926897d8a292c1e4f962ed7c9c009c3c2adda54c.
